// 风格
 const styleDes = [
    { keyword: 'assistant', emoji: '🔊', word: '助理' },
    { keyword: 'chat', emoji: '🔊', word: '聊天' },
    { keyword: 'customerservice', emoji: '🔊', word: '客服' },
    { keyword: 'newscast', emoji: '🎤', word: '新闻' },
    { keyword: 'affectionate', emoji: '😘', word: '深情' },
    { keyword: 'angry', emoji: '😡', word: '生气' },
    { keyword: 'calm', emoji: '😶', word: '冷静' },
    { keyword: 'cheerful', emoji: '😄', word: '快乐' },
    { keyword: 'disgruntled', emoji: '😠', word: '不满' },
    { keyword: 'fearful', emoji: '😨', word: '害怕' },
    { keyword: 'gentle', emoji: '😇', word: '温柔' },
    { keyword: 'lyrical', emoji: '😍', word: '抒情' },
    { keyword: 'sad', emoji: '😭', word: '伤心' },
    { keyword: 'serious', emoji: '😐', word: '严肃' },
    { keyword: 'poetry-reading', emoji: '🔊', word: '诗歌朗读' },
    { keyword: 'narration-professional', emoji: '👩‍💼', word: '专业客观' },
    { keyword: 'newscast-casual', emoji: '🔊', word: '通用随意语气发布一般新闻' },
    { keyword: 'embarrassed', emoji: '😓', word: '尴尬' },
    { keyword: 'depressed', emoji: '😔', word: '抑郁' },
    { keyword: 'envious', emoji: '😒', word: '嫉妒' },
    { keyword: 'narration-relaxed', emoji: '🎻', word: '舒缓悦耳' },
    {
      keyword: 'Advertisement_upbeat',
      emoji: '🗣',
      word: '兴奋精力充沛的推广产品或服务',
    },
    { keyword: 'Narration-relaxed', emoji: '🎻', word: '舒缓悦耳' },
    { keyword: 'Sports_commentary', emoji: '⛹', word: '体育解说' },
    {
      keyword: 'Sports_commentary_excited',
      emoji: '🥇',
      word: '快速且充满活力的播报体育赛事',
    },
    { keyword: 'documentary-narration', emoji: '🎞', word: '记录片叙事' },
    { keyword: 'excited', emoji: '😁', word: '兴奋' },
    { keyword: 'friendly', emoji: '😋', word: '友好' },
    { keyword: 'terrified', emoji: '😱', word: '害怕' },
    { keyword: 'shouting', emoji: '📢', word: '喊叫' },
    { keyword: 'unfriendly', emoji: '😤', word: '不友好' },
    { keyword: 'whispering', emoji: '😶', word: '窃窃私语' },
    { keyword: 'hopeful', emoji: '☀️', word: '充满希望' },
    { keyword: 'Default', emoji: '', word: '默认' },
  ]
  export default styleDes